project_name             = "twin"
environment              = "dev"
# bedrock_model_id         = "amazon.nova-micro-v1:0"
lambda_timeout           = 60
api_throttle_burst_limit = 10
api_throttle_rate_limit  = 5
use_custom_domain        = false
root_domain              = ""
openai_api_key           = "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"